// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SRMSS.Web.Data;

#nullable disable

namespace SRMSS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260716190000_AddEnterpriseFleetCommunicationModules")]
    partial class AddEnterpriseFleetCommunicationModules
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
#pragma warning restore 612, 618
        }
    }
}
